//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicTestFarmer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FarmerEntities : DbContext
    {
        public FarmerEntities()
            : base("name=FarmerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivitI> ActivitI { get; set; }
        public virtual DbSet<ActivitIDetail> ActivitIDetail { get; set; }
        public virtual DbSet<ActivityCategories> ActivityCategories { get; set; }
        public virtual DbSet<Chat> Chat { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Identity> Identity { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<MemberBonuss> MemberBonuss { get; set; }
        public virtual DbSet<MemberParticipation> MemberParticipation { get; set; }
        public virtual DbSet<NoticeMes> NoticeMes { get; set; }
        public virtual DbSet<OrderDetail> OrderDetail { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<OrderStatus> OrderStatus { get; set; }
        public virtual DbSet<PaymentNerhod> PaymentNerhod { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductCategoriesM> ProductCategoriesM { get; set; }
        public virtual DbSet<ProductCategory> ProductCategory { get; set; }
        public virtual DbSet<ProductCommen> ProductCommen { get; set; }
        public virtual DbSet<ProductSaleslist> ProductSaleslist { get; set; }
        public virtual DbSet<Reciever> Reciever { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<ShelvesState> ShelvesState { get; set; }
        public virtual DbSet<Shopping> Shopping { get; set; }
        public virtual DbSet<SourceInformation> SourceInformation { get; set; }
        public virtual DbSet<SubProductCategories> SubProductCategories { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<verify> verify { get; set; }
        public virtual DbSet<VerifyCheckID> VerifyCheckID { get; set; }
        public virtual DbSet<VerifyDetial> VerifyDetial { get; set; }
    }
}
