//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicTestFarmer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.MemberBonuss = new HashSet<MemberBonuss>();
            this.MemberParticipation = new HashSet<MemberParticipation>();
            this.NoticeMes = new HashSet<NoticeMes>();
            this.Product = new HashSet<Product>();
            this.ProductCommen = new HashSet<ProductCommen>();
            this.Shopping = new HashSet<Shopping>();
            this.verify = new HashSet<verify>();
        }
    
        public int UserID { get; set; }
        public string UserAccount { get; set; }
        public string UsePass { get; set; }
        public string GUID { get; set; }
        public string UserName { get; set; }
        public string UserPhone { get; set; }
        public bool UserSex { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string Adress { get; set; }
        public string EMail { get; set; }
        public Nullable<System.DateTime> RegistetedDate { get; set; }
        public Nullable<bool> Permission { get; set; }
        public Nullable<int> SourceInformationID { get; set; }
        public Nullable<int> IdentityID { get; set; }
        public Nullable<int> MemberBonus { get; set; }
    
        public virtual Identity Identity { get; set; }
        public virtual SourceInformation SourceInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberBonuss> MemberBonuss { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberParticipation> MemberParticipation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoticeMes> NoticeMes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCommen> ProductCommen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shopping> Shopping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<verify> verify { get; set; }
    }
}
