//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicTestFarmer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
        }
    
        public int OrderID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> RecieverID { get; set; }
        public string Email { get; set; }
        public Nullable<int> PaymentNerhodID { get; set; }
        public Nullable<int> OrderStatusID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string OrderRemarks { get; set; }
        public Nullable<int> Bonuss { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual PaymentNerhod PaymentNerhod { get; set; }
        public virtual Reciever Reciever { get; set; }
    }
}
